<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\MarketplaceController;
use Illuminate\Support\Facades\Route;

Route::get('/', [MarketplaceController::class, 'app'])->name('app');
Route::get('/login', [MarketplaceController::class, 'app'])->name('login');
Route::get('/register', [MarketplaceController::class, 'app'])->name('register');
Route::get('/privacy-policy', [MarketplaceController::class, 'app'])->name('privacy');
Route::get('/terms', [MarketplaceController::class, 'app'])->name('terms');
Route::get('/support', [MarketplaceController::class, 'app'])->name('support');
Route::get('/home', [MarketplaceController::class, 'app'])->name('app.home');
Route::get('/requests', [MarketplaceController::class, 'app'])->name('app.requests');
Route::get('/jobs', [MarketplaceController::class, 'app'])->name('app.jobs');
Route::get('/post', [MarketplaceController::class, 'app'])->name('app.post');
Route::get('/messages', [MarketplaceController::class, 'app'])->name('app.messages');
Route::get('/notifications', [MarketplaceController::class, 'app'])->name('app.notifications');
Route::get('/settings', [MarketplaceController::class, 'app'])->name('app.settings');

Route::post('/auth/register', [AuthController::class, 'register'])->middleware('guest');
Route::post('/auth/login', [AuthController::class, 'login'])->middleware('guest');
Route::post('/auth/logout', [AuthController::class, 'logout'])->middleware('auth');
Route::post('/api/register', [AuthController::class, 'register'])->middleware('guest');
Route::post('/api/login', [AuthController::class, 'login'])->middleware('guest');
Route::post('/api/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('guest');
Route::get('/api/auth/config', [MarketplaceController::class, 'authConfig']);
Route::post('/api/auth/social/profile', [AuthController::class, 'socialProfile'])->middleware('guest');
Route::post('/api/auth/social', [AuthController::class, 'social'])->middleware('guest');
Route::get('/api/rtc-config', [MarketplaceController::class, 'rtcConfig']);
Route::get('/api/mobile-update', [MarketplaceController::class, 'mobileUpdate']);
Route::get('/api/mobile-update/apk', [MarketplaceController::class, 'mobileUpdateApk']);
Route::get('/api/public-post/{feedPost}', [MarketplaceController::class, 'publicPost']);

Route::middleware('auth')->group(function () {
    Route::get('/api/state', [MarketplaceController::class, 'state'])->name('api.state');
    Route::post('/api/profile', [MarketplaceController::class, 'profile']);
    Route::delete('/api/account', [MarketplaceController::class, 'deleteAccount']);
    Route::post('/api/providers', [MarketplaceController::class, 'saveProvider']);
    Route::post('/api/requests', [MarketplaceController::class, 'createRequest']);
    Route::put('/api/requests/{serviceRequest}', [MarketplaceController::class, 'updateRequest']);
    Route::post('/api/requests/{serviceRequest}/offers', [MarketplaceController::class, 'offer']);
    Route::post('/api/requests/{serviceRequest}/pass', [MarketplaceController::class, 'pass']);
    Route::post('/api/requests/{serviceRequest}/confirm', [MarketplaceController::class, 'confirmRequest']);
    Route::post('/api/requests/{serviceRequest}/offers/{offer}/accept', [MarketplaceController::class, 'acceptOffer']);
    Route::post('/api/requests/{serviceRequest}/action', [MarketplaceController::class, 'action']);
    Route::get('/api/requests/{serviceRequest}/messages', [MarketplaceController::class, 'messages']);
    Route::post('/api/requests/{serviceRequest}/messages', [MarketplaceController::class, 'sendMessage']);
    Route::post('/api/requests/{serviceRequest}/typing', [MarketplaceController::class, 'typing']);
    Route::post('/api/requests/{serviceRequest}/presence', [MarketplaceController::class, 'presence']);
    Route::post('/api/requests/{serviceRequest}/messages/{message}/reactions', [MarketplaceController::class, 'messageReaction']);
    Route::get('/api/direct-conversations/{user}/messages', [MarketplaceController::class, 'directMessages']);
    Route::post('/api/direct-conversations/{user}/messages', [MarketplaceController::class, 'sendDirectMessage']);
    Route::post('/api/direct-conversations/{user}/presence', [MarketplaceController::class, 'directPresence']);
    Route::get('/api/message-summary', [MarketplaceController::class, 'messageSummary']);
    Route::post('/api/message-read', [MarketplaceController::class, 'messageRead']);
    Route::get('/api/notification-summary', [MarketplaceController::class, 'notificationSummary']);
    Route::post('/api/notification-read', [MarketplaceController::class, 'notificationRead']);
    Route::post('/api/reports', [MarketplaceController::class, 'report']);
    Route::post('/api/reports/user', [MarketplaceController::class, 'reportUser']);
    Route::post('/api/reports/job', [MarketplaceController::class, 'reportJob']);
    Route::post('/api/reports/{report}/action', [MarketplaceController::class, 'reportAction']);
    Route::post('/api/blocks/{user}', [MarketplaceController::class, 'blockUser']);
    Route::delete('/api/blocks/{user}', [MarketplaceController::class, 'unblockUser']);
    Route::get('/api/feed', [MarketplaceController::class, 'feedIndex']);
    Route::post('/api/feed', [MarketplaceController::class, 'feed']);
    Route::put('/api/feed/{feedPost}', [MarketplaceController::class, 'feedUpdate']);
    Route::delete('/api/feed/{feedPost}', [MarketplaceController::class, 'feedDelete']);
    Route::post('/api/feed/{feedPost}/share', [MarketplaceController::class, 'feedShare']);
    Route::post('/api/feed/{feedPost}/reactions', [MarketplaceController::class, 'feedReaction']);
    Route::post('/api/feed/{feedPost}/comments', [MarketplaceController::class, 'feedComment']);
    Route::post('/api/notifications/read', [MarketplaceController::class, 'markNotifications']);
    Route::post('/api/push-subscriptions', [MarketplaceController::class, 'pushSubscribe']);
    Route::post('/api/push-token', [MarketplaceController::class, 'pushToken']);
    Route::get('/api/push-status', [MarketplaceController::class, 'pushStatus']);
    Route::get('/api/route-distance', [MarketplaceController::class, 'routeDistance']);
    Route::get('/api/navigation/{serviceRequest}', [MarketplaceController::class, 'navigation']);
    Route::post('/api/activity', [MarketplaceController::class, 'activity']);
    Route::post('/api/validation/decision-signal', [MarketplaceController::class, 'validationDecisionSignal']);
    Route::post('/api/analytics/insights', [MarketplaceController::class, 'analyticsInsights']);
    Route::post('/api/validation', [MarketplaceController::class, 'validationStore']);
    Route::put('/api/validation/{entry}', [MarketplaceController::class, 'validationUpdate']);
    Route::delete('/api/validation/{entry}', [MarketplaceController::class, 'validationDelete']);
    Route::post('/api/admin/users', [MarketplaceController::class, 'adminCreateUser']);
    Route::put('/api/admin/users/{user}', [MarketplaceController::class, 'adminUpdateUser']);
    Route::post('/api/admin/users/{user}/provider-profile', [MarketplaceController::class, 'adminProviderProfile']);
    Route::post('/api/admin/users/{user}/status', [MarketplaceController::class, 'adminUserStatus']);
    Route::get('/stream', [MarketplaceController::class, 'stream']);
});
