<?php

return [
    'categories' => [
        'Plumbing',
        'Electrical',
        'Carpentry',
        'Welding',
        'Aircon & Refrigeration',
        'Appliance Repair',
        'Computer & IT Services',
        'Cellphone & Gadget Repair',
        'Cleaning Services',
        'Beauty Services',
        'Tutoring & Education',
        'Automotive Services',
        'Motorcycle Services',
        'Photography & Videography',
        'Home Improvement',
        'General Handyman',
        'Other Services',
    ],
    'urgencies' => ['Now', 'Today', 'Tomorrow', 'This week', 'Flexible'],
    'address' => [
        'region' => 'Region X (Northern Mindanao)',
        'province' => 'Misamis Oriental',
        'city' => 'City of Gingoog',
        'regions' => ['Region X (Northern Mindanao)', 'Region XIII (Caraga)'],
        'provinces' => ['Misamis Oriental', 'Independent City'],
        'cities' => ['City of Gingoog', 'City of Butuan'],
        'provinceRegions' => [
            'Misamis Oriental' => 'Region X (Northern Mindanao)',
            'Independent City' => 'Region XIII (Caraga)',
        ],
        'provinceCities' => [
            'Misamis Oriental' => ['City of Gingoog'],
            'Independent City' => ['City of Butuan'],
        ],
        'cityRegions' => [
            'City of Gingoog' => 'Region X (Northern Mindanao)',
            'City of Butuan' => 'Region XIII (Caraga)',
        ],
        'cityProvinces' => [
            'City of Gingoog' => 'Misamis Oriental',
            'City of Butuan' => 'Independent City',
        ],
        'cityBarangays' => [
            'City of Gingoog' => [
                'Agay-ayan',
                'Alagatan',
                'Anakan',
                'Bagubad',
                'Bakidbakid',
                'Bal-ason',
                'Bantaawan',
                'Barangay 1',
                'Barangay 2',
                'Barangay 3',
                'Barangay 4',
                'Barangay 5',
                'Barangay 6',
                'Barangay 7',
                'Barangay 8',
                'Barangay 9',
                'Barangay 10',
                'Barangay 11',
                'Barangay 12',
                'Barangay 13',
                'Barangay 14',
                'Barangay 15',
                'Barangay 16',
                'Barangay 17',
                'Barangay 18',
                'Barangay 18-A',
                'Barangay 19',
                'Barangay 20',
                'Barangay 21',
                'Barangay 22',
                'Barangay 22-A',
                'Barangay 23',
                'Barangay 24',
                'Barangay 24-A',
                'Barangay 25',
                'Barangay 26',
                'Binakalan',
                'Capitulangan',
                'Daan-Lungsod',
                'Dinawehan',
                'Eureka',
                'Hindangon',
                'Kalagonoy',
                'Kalipay',
                'Kamanikan',
                'Kianlagan',
                'Kibuging',
                'Kipuntos',
                'Lawaan',
                'Lawit',
                'Libertad',
                'Libon',
                'Lunao',
                'Lunotan',
                'Malibud',
                'Malinao',
                'Maribucao',
                'Mimbalagon',
                'Mimbunga',
                'Mimbuntong',
                'Minsapinit',
                'Murallon',
                'Odiongan',
                'Pangasihan',
                'Pigsaluhan',
                'Punong',
                'Ricoro',
                'Samay',
                'San Jose',
                'San Juan',
                'San Luis',
                'San Miguel',
                'Sangalan',
                'Santiago',
                'Tagpako',
                'Talisay',
                'Talon',
                'Tinabalan',
                'Tinulongan',
            ],
            'City of Butuan' => [
                'Agao Pob.',
                'Agusan Pequeño',
                'Ambago',
                'Amparo',
                'Ampayon',
                'Anticala',
                'Antongalon',
                'Aupagan',
                'Baan KM 3',
                'Baan Riverside Pob.',
                'Babag',
                'Bading Pob.',
                'Bancasi',
                'Banza',
                'Baobaoan',
                'Basag',
                'Bayanihan Pob.',
                'Bilay',
                'Bitan-agan',
                'Bit-os',
                'Bobon',
                'Bonbon',
                'Bugabus',
                'Bugsukan',
                'Buhangin Pob.',
                'Cabcabon',
                'Camayahan',
                'Dagohoy Pob.',
                'Dankias',
                'De Oro',
                'Diego Silang Pob.',
                'Don Francisco',
                'Doongan',
                'Dulag',
                'Dumalagan',
                'Florida',
                'Golden Ribbon Pob.',
                'Holy Redeemer Pob.',
                'Humabon Pob.',
                'Imadejas Pob.',
                'Jose Rizal Pob.',
                'Kinamlutan',
                'Lapu-lapu Pob.',
                'Lemon',
                'Leon Kilat Pob.',
                'Libertad',
                'Limaha Pob.',
                'Los Angeles',
                'Lumbocan',
                'Maguinda',
                'Mahay',
                'Mahogany Pob.',
                'Maibu',
                'Mandamo',
                'Manila de Bugabus',
                'Maon Pob.',
                'Masao',
                'Maug',
                'New Society Village Pob.',
                'Nong-nong',
                'Obrero Pob.',
                'Ong Yiu Pob.',
                'Pagatpatan',
                'Pangabugan',
                'Pianing',
                'Pigdaulan',
                'Pinamanculan',
                'Port Poyohon Pob.',
                'Rajah Soliman Pob.',
                'Salvacion',
                'San Ignacio Pob.',
                'San Mateo',
                'San Vicente',
                'Santo Niño',
                'Sikatuna Pob.',
                'Silongan Pob.',
                'Sumile',
                'Sumilihon',
                'Tagabaca',
                'Taguibo',
                'Taligaman',
                'Tandang Sora Pob.',
                'Tiniwisan',
                'Tungao',
                'Urduja Pob.',
                'Villa Kananga',
            ],
        ],
        'barangays' => [
            'Agay-ayan',
            'Alagatan',
            'Anakan',
            'Bagubad',
            'Bakidbakid',
            'Bal-ason',
            'Bantaawan',
            'Barangay 1',
            'Barangay 2',
            'Barangay 3',
            'Barangay 4',
            'Barangay 5',
            'Barangay 6',
            'Barangay 7',
            'Barangay 8',
            'Barangay 9',
            'Barangay 10',
            'Barangay 11',
            'Barangay 12',
            'Barangay 13',
            'Barangay 14',
            'Barangay 15',
            'Barangay 16',
            'Barangay 17',
            'Barangay 18',
            'Barangay 18-A',
            'Barangay 19',
            'Barangay 20',
            'Barangay 21',
            'Barangay 22',
            'Barangay 22-A',
            'Barangay 23',
            'Barangay 24',
            'Barangay 24-A',
            'Barangay 25',
            'Barangay 26',
            'Binakalan',
            'Capitulangan',
            'Daan-Lungsod',
            'Dinawehan',
            'Eureka',
            'Hindangon',
            'Kalagonoy',
            'Kalipay',
            'Kamanikan',
            'Kianlagan',
            'Kibuging',
            'Kipuntos',
            'Lawaan',
            'Lawit',
            'Libertad',
            'Libon',
            'Lunao',
            'Lunotan',
            'Malibud',
            'Malinao',
            'Maribucao',
            'Mimbalagon',
            'Mimbunga',
            'Mimbuntong',
            'Minsapinit',
            'Murallon',
            'Odiongan',
            'Pangasihan',
            'Pigsaluhan',
            'Punong',
            'Ricoro',
            'Samay',
            'San Jose',
            'San Juan',
            'San Luis',
            'San Miguel',
            'Sangalan',
            'Santiago',
            'Tagpako',
            'Talisay',
            'Talon',
            'Tinabalan',
            'Tinulongan',
        ],
    ],
    'statuses' => [
        'Posted',
        'Offers Received',
        'Countered',
        'Accepted',
        'In Progress',
        'Provider Marked Done',
        'Revision Requested',
        'Payment Released',
        'Rated / Closed',
        'Cancelled',
        'Disputed',
        'Resolved',
    ],
    'auto_confirm_hours' => env('KAILA_AUTO_CONFIRM_HOURS', 48),
    'rating_window_days' => env('KAILA_RATING_WINDOW_DAYS', 7),
    'web_push' => [
        'subject' => env('VAPID_SUBJECT', env('APP_URL', 'mailto:hello@example.com')),
        'public_key' => env('VAPID_PUBLIC_KEY'),
        'private_key' => env('VAPID_PRIVATE_KEY'),
    ],
    'auth' => [
        'google_client_id' => env('KAILA_GOOGLE_CLIENT_ID'),
        'facebook_app_id' => env('KAILA_FACEBOOK_APP_ID'),
        'facebook_app_secret' => env('KAILA_FACEBOOK_APP_SECRET'),
    ],
    'rtc' => [
        'ice_servers' => json_decode(env('KAILA_RTC_ICE_SERVERS', '[{"urls":"stun:stun.l.google.com:19302"}]'), true) ?: [
            ['urls' => 'stun:stun.l.google.com:19302'],
        ],
    ],
    'route_distance_url' => env('KAILA_ROUTE_DISTANCE_URL', 'https://router.project-osrm.org/route/v1/driving'),
    'mobile' => [
        'latest_version_code' => env('KAILA_ANDROID_LATEST_VERSION_CODE', 0),
        'latest_version_name' => env('KAILA_ANDROID_LATEST_VERSION_NAME'),
        'apk_url' => env('KAILA_ANDROID_APK_URL'),
        'release_notes' => env('KAILA_ANDROID_RELEASE_NOTES'),
    ],
    'native' => [
        'fcm_reuse_note' => 'Old Android FCM pieces live in C:\\laragon\\www\\kaila\\android and old server sends via FIREBASE_SERVICE_ACCOUNT_JSON/GOOGLE_APPLICATION_CREDENTIALS. Reconnect those when Capacitor native packaging is brought forward.',
    ],
];
